### ISSUE TITLE
Make it easier to paste eth addresses

### ISSUE THREAD

**Issue by katspaugh** [safe-global/safe-wallet-web#1631]
Make it easier to copy&paste addresses in our inputs by allowing pasting any text with an address and cleaning it up.

E.g.
* the user pastes `"Here's my address: 0x1234..."`
* find the `/0x[a-f0-9]{40}/` part
* remove the rest
* If the extracted address doesn't have a prefix, assume eth:. The prefix validation must remain.
* if nothing that looks like an address is found, leave it as it is as it can be an incomplete input or an ENS name

**Comment by kritarthAviate** [comment]
Hi @katspaugh! I noticed that the regex provided in the issue is incorrect as it specifies 42 characters after "0x", but Ethereum addresses are only 40 characters after "0x". I went ahead and updated the regex to reflect this, and I believe I've fixed the issue. Here's the updated regex that I used: `/(0x[a-fA-F0-9]{40})\b/`

I've read the Contribution Guidelines and Code Style Guidelines. Should I fix this and create a PR?

**Comment by katspaugh** [comment]
Hey @kritarthAviate, thanks for spotting this, I've updated the description.
Please do open the PR if you solved this issue, that would be amazing!

**Comment by kritarthAviate** [comment]
Hey @katspaugh, I have one question regarding the issue.

Right now if we enter a valid ethereum address with a prefix which is different from the current chain, it shows an error. 

Eg: input `eth:0x0000000000000000000000000000000000000000` on a goerli safe will show error - **"eth" doesn't match the current chain**

But after this fix, this won't show an error, rather it'll take the address `0x0000000000000000000000000000000000000000` and add prefix of **gor:** automatically since the address is valid.

How do we approach this edge case?
Two ways I can think of:

1. Remove the test for the network specific prefix check since we're capturing the address and cleaning up everything else.
2. Handle this edge case in the cleanup function and don't clean it if the address has some other prefix and show error.

I prefer the 1st solution since 2nd is counter-intuitive.
Please let me know your thoughts on this.

**Comment by katspaugh** [comment]
If the extracted address doesn't have a prefix, assume `eth:`.
The prefix validation must remain.

**Comment by kritarthAviate** [comment]
By this, do you mean if we're on goerli chain, we assume the prefix to be `gor:` by default and so on for all the different chains?

**Comment by katspaugh** [comment]
I meant literally "eth:" on all chains. If the user pastes it on Optimism it should show an error, which will make them double-check they are sending to the correct address on the correct chain.

That said, I think your suggestion to just paste the address as is w/o a prefix also makes sense from the convenience perspective. After all this whole feature is about convenience.

**Comment by kritarthAviate** [comment]
Hey @katspaugh , I have create a PR for this issue. Please review and let me know if the changes meet the expected results.

Also, can you please guide me on how to sign the CLA? I can't find anything [here.](https://github.com/safe-global/web-core/blob/dev/safe.global/cla)

**Comment by katspaugh** [comment]
Thanks for the PR! Please read what the CLA bot commented there, it wants you to write a magic comment.

**Comment by katspaugh** [comment]
@francovenica I've merged a fix to dev, please test on there.

**Comment by francovenica** [comment]
The prefix validation doesn't work on inputs in the settings pages: add owner, replace owner, spending limits.

if you paste "eth:0x1234...abcd" on a network that is NOT Eth it will add the correct prefix, which is something that it shouldn't do, it should tell me that "eth is not a valid prefix".

It works fine in modals like "send funds", so maybe those are coded differently?

In the gif you can see that first I paste an address with the wrong prefix in send funds and it works fine, it tells me the prefix is wrong, but when I do it in add owners the error doesn't pop up
![prefix](https://github.com/safe-global/safe-wallet-web/assets/4503659/8fd97477-e6f2-4e03-aebd-bbb6e2f41da0)

**Comment by katspaugh** [comment]
@francovenica it's the same on prod, so it's not related to the changes in #1897. I suggest we close this issue and open a new one.
