### ISSUE TITLE
[EIP1271] Show shareable links in MsgModal and history

### ISSUE THREAD

**Issue by katspaugh** [safe-global/safe-wallet-web#2020]
Use this endpoint (routed via CGW) to fetch message details:
https://safe-transaction-goerli.safe.global/api/v1/messages/0x7f4032fd13f27c5fce4694a1a6b79f65c68656da4eee4347a414f5bcec915b39/

Create a deep link page for Message details.

Link to it from the Message popup and History.
<img width="530" alt="Screenshot 2023-05-22 at 13 40 25" src="https://github.com/safe-global/safe-wallet-web/assets/381895/fcbd6239-f185-4fec-b6ed-3a29467db91d">

## Designs
[screen view](https://www.figma.com/file/cMDccuR9aZFqAiBd4dKsKg/Transaction-flow?type=design&node-id=1%3A15710&mode=design&t=FLMcU43UXdbatjOb-1)
[states](https://www.figma.com/file/cMDccuR9aZFqAiBd4dKsKg/Transaction-flow?type=design&node-id=1%3A16071&mode=design&t=FLMcU43UXdbatjOb-1)

**Comment by coffeexcoin** [comment]
Would love to see this implemented. As far as I can tell, at this moment in time there is no way to have multiple signers in different physical locations with different devices sign the same EIP1271 signature from a WalletConnect session.

This blocks the ability to login to any service that requires a signature to authenticate.

**Comment by jmealy** [comment]
The message only gets created once it get's the first signature, so we can only show the share link after it gets signed. But it would be easy to miss the link appearing since it's up at the top of the page. What about displaying the message link in this block instead, so it's easier to see?



![Image](https://github.com/safe-global/safe-wallet-web/assets/17801424/260dbfd9-9133-4e85-b45b-bbdb851d0e0b)

**Comment by TanyaEfremova** [comment]
This was indeed intended by design, the message to share the link is shown[ like this](https://www.figma.com/design/cMDccuR9aZFqAiBd4dKsKg/Transaction-flow?node-id=1-15710&t=cCOW54XMXKNGDMXJ-1)

We can combine both, since the message isn't really clear IMO. I think, the sentence _Share the link with other owners_ can help
