### ISSUE TITLE
Safes made directly on contract factory are broken

### ISSUE THREAD

**Issue by divine-comedian** [safe-global/safe-wallet-web#2480]
## Bug description
As a DAO I want to be able to have the same address for my safe on all chains. This make it easier for using things line ENS names, prevents funds being sent to the wrong address and generally just makes them easier to keep track of. 

You can do this currently by calling the same tx data on the gnosis contract factory on the chain of choice. It will reproduce the multisig with the same address, signers, threshold, singleton/implementation etc.. 

However these multisigs are barely functional from the Safe UI - it is a struggle to make, sign and execute txs - sometimes it works and sometimes it doesn't - usually we troubleshoot by refreshing the page and every 1/1000 tries it works :laughing:  

So something is sort of working... but also not - not sure what the heck is going on. Ideally assuming the implementation contract is safe shouldn't this just work? 

Here's an example safe I made:
https://app.safe.global/home?safe=oeth:0xf924fF0f192f0c7c073161e0d62CE7635114e74f

Here's the creation tx:
https://optimistic.etherscan.io/tx/0xf2f73df01a8c7d7817f68b1a05bd7b67bf660405cf55fe725b6bc1d058e97643

You can see the singleton is the same as the one currently being used by default on the contract factory:
https://optimistic.etherscan.io/address/0xa6b71e26c5e0845f74c812102ca7114b6a896ab2

Interesting enough we can do MOST things through third party multisig apps such as [onchainden.com](https://app.onchainden.com/safes)

I've also tried changing the master copy using the CLI to: 
https://optimistic.etherscan.io/address/0xfb1bffC9d739B8D520DaF37dF666da4C687191EA

However it looks like I am unable to do it right now because the cli keeps crashing:
https://github.com/5afe/safe-cli/issues/246

## Environment
 - Browser: Brave, Safari, Firefox
 - Wallet: MetaMask
 - Chain: Optimism

## Steps to reproduce
 1. Find Safe on Mainnet on etherscan
 2. copy singleton & data from creation transaction
 3. go to contract factory on L2 or sidechain
 4. createProxy with copied singleton & data
 5. Check safe on  safe web UI
 6. Attempt to create transaction / Sign transaction

## Expected result
Users should be able to use their Safe normally even if they didn't make it directly through the UI

## Obtained result
Safes are pretty much unusable when created in this manner from the Safe web UI

## Screenshots
![image](https://github.com/safe-global/safe-wallet-web/assets/67759413/68619117-e3b4-46a1-a752-74acce337549)

![image](https://github.com/safe-global/safe-wallet-web/assets/67759413/a5dffe10-62e6-4f38-a84a-f55cf66d73a4)

![image](https://github.com/safe-global/safe-wallet-web/assets/67759413/4a1d75ec-0b7d-42e4-a894-fd3f39a3231b)

**Comment by katspaugh** [comment]
The Optimism [proxy factory](https://github.com/safe-global/safe-deployments/blob/main/src/assets/v1.3.0/proxy_factory.json) isn't deployed to the same address as the mainnet one. We support only our official deployments in our services. With unofficial ones, the backend doesn't work, and that's why we display these warnings. Even you manage to upgrade your mastercopy using the CLI, it won't make the Safe functional in our UI because the backend won't be able to index it.

Also on some chains like zkSync it's not even possible to deploy a proxy factory to the same address deterministically, so you can't have the same Safe address across _all_ chains.

Please also see [this discussion](https://forum.safe.global/t/how-can-a-safe-hold-asset-on-multiple-chains/2242) if you're interested in the topic. Some of the ideas there involve using ENS, which you also mentioned, but cross-chain ENS resolution isn't common yet. We might introduce a solution for this in future.

Hope this helps.

**Comment by divine-comedian** [comment]
Got it, that is very unfortunate.

Interesting observation as well is the proxy factory you linked has around 75k transactions while the other one has 1.2 million transactions!
