### ISSUE TITLE
Use `0` for salt nonce.

### ISSUE THREAD

**Issue by MicahZoltu** [safe-global/safe-wallet-web#2989]
https://github.com/safe-global/safe-wallet-web/blob/f1621751cc4c815717ed80d5c2a3f33965d505e6/src/components/new-safe/create/index.tsx#L171

Currently, when a user creates a safe the current timestamp is used as a nonce.  Unfortunately this means that there is no way to find previously created safes without indexing all event history, which either requires a very heavy amount of work on the RPC server and a long wait for users or requires the user connect to some kind of indexing service (almost certainly centralized).

By using `0` for the salt by default, if a user attempts to create a safe with the same parameters as a safe they previously created (e.g., a simple 1 of 1 safe) the app can detect the already existing safe, check to see if it is still owned by the user, and ask if they want to add that safe to the UI instead.  If they choose to proceed, the `saltNonce` can simply be incremented by 1.  If the user has many safes, the UI can walk the nonces until it finds a free one and show the user all of the already existing safes they have.

This solution won't work in all cases, because users have SAFEs already created with an old nonce, and safes created with different proxy contracts (though all prior proxies used in a UI with `saltNonce = 0` could be easily searched) or the user may create a multisig from the start.  However, it handles the common end-user case of "1 of 1 with social recovery" quite well and in a censorship resistant way.

While I can appreciate the simplicity of using `Date.now()` for the nonce, it is quite bad for censorship resistance as it makes it very difficult for regular users to find their already existing SAFE addresses without centralized services.

**Comment by katspaugh** [comment]
cc @usame-algan this might help with counterfactual deployment too, if the user loses their locally stored CREATE2 params.

**Comment by usame-algan** [comment]
Thanks for looking into this @MicahZoltu!

Starting with [v1.30.0](https://github.com/safe-global/safe-wallet-web/releases/tag/v1.30.0), all safe deployments will have an incremental `saltNonce`. Here is some technical detail on how we achieve this.

On safe creation:
1. Predict the `safeAddress` starting with `saltNonce = 0`
2. Check on-chain if a contract is deployed to that address
3. If not, use that saltNonce and create the safe
4. Otherwise increase the saltNonce by 1 and do Steps 1-3 again

Although we still fetch owned safes from our services, this should make it easier for future Safe Accounts to be recoverable without a central service.

**Comment by MicahZoltu** [comment]
Awesome to hear, thanks!

It may be worthwhile to let the user know "We found these other SAFEs created by you, do you want to create another or use one of them?", but that is entirely a UI/UX issue that could be thought about later.

**Comment by katspaugh** [comment]
Thanks @MicahZoltu, I've created a separate issue for that, see the link above.

And many thanks for the fixed nonce idea, this helped us a lot when building the counterfacual Safe creation feature. 🙏
