### ISSUE TITLE
Assets page doesn't load when changing currency to SATS

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-wallet-web#3045]
Issue Category
Safe loading issue, doesnt load on any interface

What happened?
Encountering an error when changing the currency to SATS, the Assets page fails to load afterward. This issue seems to affect most networks.
image

Date and time this happened or you first noticed this issue
18-12-2023 4:22pm

Network
Ethereum Mainnet

Safe Address
No response

Token Address
No response

Token Type
None

Transactions
No response

**Comment by compojoom** [comment]
I had a look at this issue and although the reason why it crashes is simple, the fix for it is right now "unclear" to me. 

The app crashes, because the [Intl.NumberFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat#style_options) when used to format a currencyl expectes an ISO 4217 currency. I'm not sure about the exact standard specification and whether the 3 Letters for the currency are pre-determined, but actually any 3 letter code would work fine (no matter if it is a fiat currency or a crypto currency e.g. ETH, BTC etc).

The problem comes when you pass a currency code such as SATS (or BITS) - basically for anything that is 4 letters Intl.NumberFormat throws an exception and that's why we get the crash. 

The crash can happen in 2 locations:
https://github.com/safe-global/safe-wallet-web/blob/dev/src/utils/formatNumber.ts#L126

and:
https://github.com/safe-global/safe-wallet-web/blob/dev/src/utils/formatNumber.ts#L180

Catching the exception in the denominator could be easy:

```
const getMinimumCurrencyDenominator = memoize((currency: string): number => {
  const BASE_VALUE = 1

  try {
    const formatter = new Intl.NumberFormat(undefined, {
      style: 'currency',
      currency,
    })

    const fraction = formatter.formatToParts(BASE_VALUE).find(({ type }) => type === 'fraction')

    // Currencies may not have decimals, i.e. JPY
    return fraction ? Number(`0.${'1'.padStart(fraction.value.length, '0')}`) : 1
  } catch (e) {
    // Intl.NumberFormat works for currencies that follow the ISO 4217 standard, or technically
    // any 3 character currency code. However, we might have currencies with 4 characters, e.g. SATS, BITS
    return 1
  }
})
```

I guess it would be even ok, since if there is no fraction we actually always return 1.

The currency formatter on the other hand is more complicated. 

```
    const formatter = new Intl.NumberFormat(undefined, options)

    const parts = formatter.formatToParts(float) // Returns an array of objects with `type` and `value` properties

    const fraction = parts.find(({ type }) => type === 'fraction')
```

I'm not sure what we are to expect from such a call for a currency such as BTC, ETH or the one that is crashing the whole thing: SATS? 

for SATS it is clear taht parts won't work, so we have to define the parts object array the way we want it? I did some checks and for example:

<img width="720" alt="grafik" src="https://github.com/safe-global/safe-wallet-web/assets/693770/fae254f9-ae42-4432-91b1-34967bd8ac7a">

So obvisouly the numberFormat doesn't have a notion of Bitcoin or how it should format it. 

Putting that asside:
We receive the list of currency by a call to coingecko (through the client gateway). Since our formatCurrency function also claims that it expects an ISO 4217 currency we could theoretically strip anything that is not ISO 4217 currency on the client gateway. 

Can someone with better overview of the whole system point me to the correct term of action here?
maybe @iamacook or @katspaugh ?
