### ISSUE TITLE
Strange behavior when signing with walletconnect

### ISSUE THREAD

**Issue by compojoom** [safe-global/safe-wallet-web#3133]
## Bug description
We have 2 safes: Parent(P) & Child(C). The owner of the C is P. The owner of P is a normal EOA account. l

We connect C to P with Walletconnect(Connect wallet -> Wallet Connect -> copy paring code/link, then in P use the Walletconnect icon in the toolbar and enter the Pairing code). 

Then in C we propose a new TX.

![grafik](https://github.com/safe-global/safe-wallet-web/assets/693770/be37f058-1a65-496b-a723-0c26bcbd58f8)

The tx appears in P and we are able to sign:
![grafik](https://github.com/safe-global/safe-wallet-web/assets/693770/5a858858-4d67-4667-8f8c-47e8db14a787)

When we sign the TX window in C closes and we no longer can see the TX anywhere.

In P the "confirm transaction" window also dissapears, but we can find the TX under pending.

## Environment
 - Browser: Not browser specific
 - Wallet: MetaMask & Walletconnect
 - Chain: non-chain specific

## Steps to reproduce
Check bug description above

## Expected result
I would expect that the signed TX would somehow be visible in the child safe.

## Obtained result
Signed TX is not visible in the safe.

**Comment by katspaugh** [comment]
When signing a Safe tx with a Safe, it's still not using the native offchain signing, it's doing an onchain signature instead. This signature will appear only when indexed.  So if you're creating a new tx (as opposed to signing an existing one), it will appear in the queue only once the onchain signature is indexed.

Solution: enable offchain signing for nested Safe signers.

**Comment by usame-algan** [comment]
I think it is correct that both windows close but the transaction should appear in the Queue of P since its only been signed in P and once executed in P, the transaction in the queue of C should increase in confirmation count since that one also was only signed and not executed.

Thinking about this, its quite confusing and I would suggest we document each possible case and what behaviour we expect e.g.

1. Execute in C, Sign in P
2. Execute in C, Execute in P
3. Sign in C, Execute in P
4. Sign in C, Sign in P

**Comment by katspaugh** [comment]
Closing because Nested Safe support is now a separate epic, so this will be addressed holistically.
