### ISSUE TITLE
TX execution doubles categories/txs on UI while execution is in progress

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-wallet-web#3215]
## Bug description
Bulk execution doubles categories/txs on UI while execution is in progress

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Sepolia

## Steps to reproduce
 1. Add a few txs in queue and sign fully
 2. click bulk execution with relay -> start the process
 3. check the queue view
 Current result: 
 The queue list contains:
 pending
queued
 next
 queued
categories at the same time and the txs are displayed twice on UI

## Expected result
Make sure that the categories and txs are not doubled , as this is quite confusing 
## Screenshots
<img width="644" alt="image" src="https://github.com/safe-global/safe-wallet-web/assets/338622/50ee3626-0a74-42e7-92f2-8e4e97cda427">

**Comment by TanyaEfremova** [comment]
I think, we could bundle these transactions under _Pending_ category. Otherwise, it looks like other transactions are not pending and require action.

**Comment by katspaugh** [comment]
The pending queue is shown on top of the regular queue for pending txs in 1/X Safes.

If a transaction from that queue is signed, it will be present also in the normal queue. We should not show signed txs in the pending queue.

**Comment by usame-algan** [comment]
I think ideally we would only have one list of transactions and just switch their status to pending and remove all labels like Next/Queued and only have one label at the top saying Pending. The reason we have a pending queue on top for 1/n safes is because it is possible to immediately execute transactions which don't show up in the normal queue so we have to fetch the untrusted queue to show those. 

However, when bulk executing we can be certain that all transactions are fully signed so there is no need to display this pending queue on top. So for a quick fix we could disable the pending queue for bulk execution i.e. if more than one transaction is pending.

For a more general fix we could try only showing pending queue items if they are unsigned (0 of n confirmations) or hide signed transaction from the normal queue if they are pending.
