### ISSUE TITLE
transaction duplication in case of relayer error

### ISSUE THREAD

**Issue by Pasha8914** [safe-global/safe-wallet-web#3422]
## Bug description
During the transaction "approve" sending, 2 "approve" transactions were created in the transaction queue (when 
I used a relayer).

## Environment
 - Browser: Chrome
 - Wallet: WalletConnect + Metamask
 - Chain: Sepolia

## Steps to reproduce
 - Create approve transaction
 - Select __Sponsored by Safe__
 - Try to execute

## Expected result
transaction execution
## Obtained result
2 signed transactions require execution, WalletConnect will return a GnosisSafe Tx Hash from the sendTransaction function for a transaction with a higher nonce.

https://github.com/safe-global/safe-wallet-web/assets/43392281/02dda1df-ba24-4d02-a0cf-5f06f80658ce

If you try to execute a transaction with a higher nonce, you will catch an error.

<img width="1492" alt="image" src="https://github.com/safe-global/safe-wallet-web/assets/43392281/16761ab5-6155-42af-aaf0-2a65865a076f">

After several attempts to "execute", the transaction with the higher nonce disappears. (transaction with nonce 115 is in the video, but it's not in the screenshot.)

<img width="1487" alt="image" src="https://github.com/safe-global/safe-wallet-web/assets/43392281/f79b983f-18bb-4165-94c1-e5720469bea7">

<img width="1483" alt="image" src="https://github.com/safe-global/safe-wallet-web/assets/43392281/165bab68-0f3b-4c4a-8daa-f021f932ff9c">

**Comment by usame-algan** [comment]
@Pasha8914 thanks for reporting! There was an issue with the relay service that should now be resolved. Can you try again?

As for the UX flow, what happens is that the transaction is first signed (Only signed transaction can be relayed) and then proposed to the backend service (To show up in the queue) but then the call to the relay service fails. The transaction dialog stays open though and even updates the nonce which is not ideal imo.

I think a slightly better way of handling this is to close the transaction dialog in case the relay call fails since the transaction is already queued at this point.
